name: Production-Tag-Build-Deploy

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Tag to be built with'     
        required: true
        default: ''

jobs:
    
  create-release:
    runs-on: ubuntu-latest
    env: 
     RELEASE_TAG: ${{ github.event.inputs.releaseTag }}
    steps:
    - name: Install Go   
      uses: actions/setup-go@v2
      with:
        go-version: "1.16.x"
    - name: Checkout code   
      uses: actions/checkout@v2
    - name: Setup LibUsb
      run: sudo apt install -y libusb-1.0-0-dev libusb-1.0-0
    - name: Build
      run: |
        go build
        touch version.txt
        echo "${{ steps.create_release.outputs.current_tag }}" > "version.txt"
        zip go-adb.zip go-adb 91-android.rules go-adb.service version.txt
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: go-adb.zip
        asset_name: go-adb.zip
        tag: ${{ env.RELEASE_TAG }}
        overwrite: true               

    